// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    activity_by_weekday_hour: {
        name: "activity_by_weekday_hour";
        parameters: Record<string, never>;
        result: unknown;
      };
    activity_daily: {
        name: "activity_daily";
        parameters: Record<string, never>;
        result: unknown;
      };
    activity_daily_message_trend: {
        name: "activity_daily_message_trend";
        parameters: Record<string, never>;
        result: unknown;
      };
    activity_daily_voice_trend: {
        name: "activity_daily_voice_trend";
        parameters: Record<string, never>;
        result: unknown;
      };
    activity_summary_kpis: {
        name: "activity_summary_kpis";
        parameters: Record<string, never>;
        result: unknown;
      };
    channel_activity: {
        name: "channel_activity";
        parameters: Record<string, never>;
        result: unknown;
      };
    user_activity: {
        name: "user_activity";
        parameters: Record<string, never>;
        result: unknown;
      };
    user_messages_ranking: {
        name: "user_messages_ranking";
        parameters: Record<string, never>;
        result: unknown;
      };
    user_voice_ranking: {
        name: "user_voice_ranking";
        parameters: Record<string, never>;
        result: unknown;
      };
  }
}
